// Generated by CoffeeScript 1.12.7
(function() {
  exports.myVar = "myVariable";

  exports.myFunction = function() {
    return print("myFunction is running");
  };

  exports.myArray = [1, 2, 3];

}).call(this);
